=== louishll/Site_projet_techno_web/XML/xml nico/perso.dtd
<!ENTITY factions "(Griffondor|Serdaigle|Poufsouffle|Serpentard)">
<!ENTITY side  "(gentil|mÃ©chant|neutre)">

<!ELEMENT xml (perso)>

<!ELEMENT perso (personnaldata,faction?,side,actor,BFF*)>
<!ATTLIST perso 
    gender (male|female) #IMPLIED>

<!ELEMENT personnaldata (name,firstname+,img)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT firstname (#PCDATA)>

<!ELEMENT img EMPTY>
<!ATTLIST img
    url CDATA #REQUIRED
    title CDATA #REQUIRED>

<!ELEMENT faction (#PCDATA)>
<!ATTLIST faction id %factions; #REQUIRED>

<!ELEMENT side EMPTY>
<!ATTLIST side id %side; #REQUIRED>

<!ELEMENT actor (#PCDATA)>

<!ELEMENT BFF (#PCDATA)>

=== louishll/Site_projet_techno_web/XML/xml nico/perso.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml SYSTEM "perso.dtd">
<xml>
    <perso gender="male">
        <personnaldata>
            <name>Potter</name>
            <firstname>Harry</firstname>
            <img url="harry_potter.jpg" title="harry potter jeune"/>
        </personnaldata>
        <faction id="Griffondor">Griffondor</faction>
        <side id="gentil"/>
        <actor>Daniel Radcliffe</actor>
        <BFF>Hermione Granger</BFF>
        <BFF>Ron Weasley</BFF>
    </perso>
</xml>
